image: nixos/nix

stages:
- discover
- trigger

before_script:
- mkdir -vp ~/.config/nix
- echo "experimental-features = nix-command flakes" > ~/.config/nix/nix.conf

discover:
  stage: discover
  script:
    - nix run github:jzbor/cornflakes#gitlab-ci-discover
  artifacts:
    expire_in: 1 hour
    paths:
      - dynamic-gitlab-ci.yml

trigger:build:
  stage: trigger
  trigger:
    include:
      - artifact: dynamic-gitlab-ci.yml
        job: discover
    strategy: depend

